version: '3.8'

services:
  app:
    build:
      context: .
      target: builder # Use the builder stage for development
    ports:
      - "5000:5000"
    # These environment variables override values from .env file
    # They are kept here to ensure correct container connectivity
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/blueearth
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    command: npm run dev
    
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blueearth
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      
volumes:
  postgres_data:
  redis_data: