#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged to handle staged files
npx lint-staged

# Run TypeScript check on the entire project
node scripts/lint-and-type-check.mjs --type-only --quiet